### ISSUE TITLE
overcoming Mac OS X installation errors

### ISSUE THREAD

**Issue by phette23** [pitthsls/pycounter#12]
First off, thanks so much for this work! There's a real lack of good COUNTER/SUSHI tooling and I can't wait to try pycounter out.

This isn't an active issue (feel free to close immediately), but documentation in case you get questions or issues related to installation on Mac OS X. `pip` at first reported it couldn't find a matching version ("Could not find a version that satisfies the requirement pycounter (from versions: 0.5a1, 0.5a2)"), and then the lxml extension wouldn't build ("fatal error: 'libxml/xmlversion.h' file not found" "error: command 'cc' failed with exit status 1"). Here's how I got around these problems:

### `pip` version

Upgrade pip to latest, `pip install pip --upgrade`, should work. Didn't try with `pip3`.

### lxml compilation

- have XCode command-line tools installed so you have a compiler, `xcode-select --install`
- install libxml2 and libxslt (via homebrew), `brew install libxml2 libxslt`
- since OS X already ships with those libraries, they're not symlinked by default, override that with `brew link libxml2 libxslt --force`
- _now_ pycounter will install & the lxml dependency builds
- undo the symlinking with `brew unlink libxml2 libxslt`, just in case it affects other software

Not sure if that'll ever come in handy, but if other users have the same issue it might help. Thanks again!

**Comment by Wooble** [comment]
Good point; I doubt `pip install lxml` will actually work on most platforms out of the box; I don't think even most linux distros will include the appropriate devel packages needed in a base install. I will update the documentation to point out the needs for lxml's dependencies.

I believe the version problem is because some earlier versions of pip didn't like to install pre-release software. 

I will investigate both and update the docs.
