### ISSUE TITLE
Failures for non-UTF-8 CSV files

### ISSUE THREAD

**Issue by Wooble** [pitthsls/pycounter#26]
(godmar writes):
> what's your strategy of dealing with counter reports that are not UTF-8?
> So far, for the random batch of JR1 reports I have, 195 parse ok with pycounter (with the patches in the gist). 328 fail to parse, the majority because the file is not UTF-8.
> 
> One strategy is to try to iconv the file before injection, which may work if the file's encoding is known.
> 
> pycounter right now seems to insist on valid UTF-8 for files ending in .csv.
> 
> What do you think the best strategy is?

**Comment by Wooble** [comment]
UnicodeReader has support for specifying an encoding; adding an encoding argument to `parse()` and `parse_separated()` defaulting to utf-8 and passing it along is one option.

Possibly also use chardet to detect an encoding if the given encoding fails to parse (although I don't know how reliable it is at guessing the right encoding; maybe we could never just fall back to using replacement characters for things that won't parse, possibly issuing a warning)

Unless I'm missing something, COUNTER doesn't actually specify the encoding (SUSHI specifies UTF-8), so I mildly surprised I haven't been bitten by this one yet.

**Comment by godmar** [comment]
I took a second look. Only 41 of the remaining 265 failures are due to UnicodeDecodeErrors.

I don't expect there to be a great variety of character sets represented, really probably only ISO 8859-1 (assuming the file is not complete garbage) - perhaps we could try a 8859-1 decode fallback if utf-8 decode fails, on a field-by-field basis. If we change csvhelper like that, however, Python 3 will have to be rethought. I find it also unreasonable to expect that the user would know the encoding. chardet might be an option, I've never used it.

(I'm still looking at the other failures - many are due to Macintosh line ending (\r); conceivably we could open the file using 'rU' instead of 'rb' in Python 2.)

**Comment by godmar** [comment]
Yeah, https://gist.github.com/godmar/891749b267ab74d3268f makes all 41 of my decoding errors go away.

**Comment by Wooble** [comment]
Hmm. The csv documentation says the file must be opened with the `b` flag on platforms where it matters, but the test suite seems to pass on Windows with the `U` flag instead, so... LGTM.

**Comment by godmar** [comment]
Ignore the 'U' part.

I've since learned that the .csv files I've been debugging with do not actually represent "real-world" files, but may or may not have been touched by humans (e.g., using Excel or Word on Windows or Mac).  So I feel much less comfortable about suggesting anything relevant to pycounter at this point :-(

**Comment by Wooble** [comment]
(b4b8c46 takes a conservative approach of providing a way to specify the encoding you actually have; I'm taking a look at whether chardet is likely to be reliable enough to automatically guess the encoding)

**Comment by godmar** [comment]
Again, my apologies for confusing "real-world" JR1 with possibly tainted ones (e.g., those saved with Excel's "Save as .csv" feature that produces ANSI/ISO 8859-1/latin-1).

However, I am increasingly certain that some real-world files downloaded via vendor interface are, in fact, encoded in this way. (I've seen at least one example: Project Muse, which I know wasn't touched.)

To comment on your patch: I'm skeptical: it seems that specifying the encoding is less than useful, because of how the surrounding client side code would look. It would have to either know the encoding (which in practice isn't true (?)), or would have to catch the unicodedecode error and retry.

What are your thought on this: specify an optional "fallback_encoding" - if given, and if Unicode decoding fails, try decoding using the encoding whose value is specified.

**Comment by Wooble** [comment]
Allowing a specified fallback_encoding (and defaulting it to latin-1, which can accept any bytes and possibly just do the wrong thing with them...) sounds attractive.

**Comment by godmar** [comment]
To address the risk of trying to decode what is essentially garbage, what if you left the fallback encoding default empty, but caught and reraised the UnicodeDecodeError, after printing a msg asking the user to consider a fallback encoding if they believe latin-1 is a sensible one? Might be overkill.

**Comment by Wooble** [comment]
Maybe adding a warning when there's a fallback instead? I think in the vast majority of cases the file will actually be latin-1, or the user doesn't care that their titles are ugly since they're probably matching records on ISSN and care about the usage numbers more than the titles anyway.

(If you pass in a UTF-16 file, the decoding will work when it shouldn't, but things are going to fail fast anyway when there are no separators anywhere in the file)

**Comment by Wooble** [comment]
(I added a warning in 5b0c2ea )
