### ISSUE TITLE
Parsing COUNTER5 reports

### ISSUE THREAD

**Issue by MarkEEaton** [pitthsls/pycounter#98]
When I follow this example from the README,

    import pycounter.report
    report = pycounter.report.parse("COUNTER4_2015.tsv")  # filename or path to file

COUNTER5 `.json` files do not parse, and throw an `UnknownReportTypeError`. 

I've gathered these json files myself with `curl` and `requests.get(url)`. Should I be using `pycounter.sushi.get_report()` for COUNTER5? The caveats from the README make me wary of doing that. Does it do something special that makes reports parseable?

**Comment by Wooble** [comment]
Mark,

Sorry for the delayed response; I haven't been able to devote the time I'd like to this project lately.

Unfortunately, the same caveats from the README will apply no matter how you get the data, as the problem is with the object structures currently in pycounter not being redesigned from the ground up to handle the new design of COUNTER 5. `pycounter.sushi5.raw_to_full()` is currently the way to get a CounterReport object from the JSON you'd get from a COUNTER 5 SUSHI server (it takes a dict decoded from that JSON.) The resulting report object is the same Frankenstein's monster COUNTER 4-ish thing you get from making the SUSHI call directly from pycounter.

My hope has been that a final 3.0 release will finally fix this, but I don't have a timeline for that as I've been working almost entirely on our upcoming ILS migration.

**Comment by MarkEEaton** [comment]
TY for the clarification and udpate! That is helpful info
